// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWW5jFZxst5tXWuVZd7Be3q3lJ1eFQ-c',
    appId: '1:266186581069:web:8a3bfa4ff50df34691a804',
    messagingSenderId: '266186581069',
    projectId: 'tawsilidriver',
    authDomain: 'tawsilidriver.firebaseapp.com',
    storageBucket: 'tawsilidriver.firebasestorage.app',
    measurementId: 'G-8C9YL9RGZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQ3ppad0hqAQwGbvo3R6N8oP1sGoshn8',
    appId: '1:266186581069:android:a8a8d9e98c3fbdb991a804',
    messagingSenderId: '266186581069',
    projectId: 'tawsilidriver',
    storageBucket: 'tawsilidriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp7-qo0xpMbr4d9-oaXumC2qTvlu6BXw',
    appId: '1:266186581069:ios:e82b5ee0312cfc2a91a804',
    messagingSenderId: '266186581069',
    projectId: 'tawsilidriver',
    storageBucket: 'tawsilidriver.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyp7-qo0xpMbr4d9-oaXumC2qTvlu6BXw',
    appId: '1:266186581069:ios:e82b5ee0312cfc2a91a804',
    messagingSenderId: '266186581069',
    projectId: 'tawsilidriver',
    storageBucket: 'tawsilidriver.firebasestorage.app',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUWW5jFZxst5tXWuVZd7Be3q3lJ1eFQ-c',
    appId: '1:266186581069:web:2450ce593856b58d91a804',
    messagingSenderId: '266186581069',
    projectId: 'tawsilidriver',
    authDomain: 'tawsilidriver.firebaseapp.com',
    storageBucket: 'tawsilidriver.firebasestorage.app',
    measurementId: 'G-QX787GQZF4',
  );
}
